default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: quotes_app_development

test:
  <<: *default
  database: quotes_app_test

production:
  <<: *default
  database: quotes_app
